version: '3'

services:
  migrate:
    build:
        dockerfile: Dockerfile.dev
        context: .
    command: python manage.py migrate
    volumes:
      - ./app:/usr/src/app
  runserver:
    build:
        dockerfile: Dockerfile.dev
        context: .
    volumes:
      - ./app:/usr/src/app
    environment:
      - DEBUG=True
      - DEV_MODE=True
    ports:
      - "8000:8000"
    depends_on:
      - migrate
